using HarmonyLib;
using Verse;
using RimWorld;
using System.Collections.Generic;

namespace Mashed_Ashlands
{
    /// <summary>
    /// Prevents certain mineable things from being generated by meteorites
    /// </summary>
    [HarmonyPatch(typeof(ThingSetMaker_Meteorite))]
    [HarmonyPatch("Generate")]
    public static class ThingSetMaker_Meteorite_Generate_Patch
    {
        [HarmonyPrefix]
        public static bool Mashed_Ashlands_ThingSetMaker_Meteorite_Patch(ref List<ThingDef> ___nonSmoothedMineables)
        {
            if (!___nonSmoothedMineables.NullOrEmpty())
            {
                for (int i = ___nonSmoothedMineables.Count - 1; i >= 0; i--)
                {
                    BuildingProperties props = BuildingProperties.Get(___nonSmoothedMineables[i]);
                    if (props != null && !props.canBeMeteorite)
                    {
                        ___nonSmoothedMineables.RemoveAt(i);
                    }
                }
            }
            return true;
        }
    }
}
